name: record_android
description: Android specific implementation for record package called by record_platform_interface.
version: 1.3.1
homepage: https://github.com/llfbandit/record/tree/master/record_android
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    path: ../record_platform_interface

flutter:
  plugin:
    implements: record
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
