name: record_linux
description: Linux specific implementation for record package called by record_platform_interface.
version: 0.7.2
homepage: https://github.com/llfbandit/record/tree/master/record_linux
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    path: ../record_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: record
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
        dartPluginClass: RecordLinux
